CSS Здравствуйте
ok-technopolis-autumn-2019/Abdulla_Akhmedov pull request #2
Opened 2019-10-22 20:24 UTC by Eretic431

:tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan: :tajikistan:

2019-10-24 17:03 UTC, fromanywhere requested changes
Очень важно починить фокусы

2019-10-24 17:03 UTC, fromanywhere commented on index.html
> +            <div class="todos-list_item __completed">
Хорошо!

2019-10-24 17:03 UTC, fromanywhere commented on styles/base/custom-cancel-button/custom-cancel-button.css
> +.todos-list_item_remove {
нейминг приводим к БЭМ

2019-10-24 17:03 UTC, fromanywhere commented on styles/base/custom-cancel-button/custom-cancel-button.css
> +	  outline: none;
Здесь был убит фокус

2019-10-24 17:03 UTC, fromanywhere commented on styles/base/custom-checkbox/custom-checkbox.css
> +	background: url(../../../images/completed.png);
Не забываем про ретину — если растр, то через media queries

2019-10-24 17:03 UTC, fromanywhere commented on styles/base/custom-textarea/custom-textarea.css
> +	overflow: hidden;
а что мне делать, если текста будет много?

2019-10-24 17:03 UTC, fromanywhere commented on styles/base/main.css
> +	max-width: 550px;
минимальную ширину бы тоже зафиксировать

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todo-board/todo-board.css
> +    display: block;
не очень понял здесь

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +		background: url(	background: url(../../../images/select-all.png) no-repeat 0 0;
тут что-то пошло не так

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +	outline: none;
убит фокус

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +.todo-creator_text-input::-webkit-input-placeholder {
можно один раз без префиксов, автопрефиксер сам всё поставит, как на последней лекции показывал

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +	visibility: visible;
а на фокус?

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +	padding: 10px;
здесь все шрифты послетали

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +.filters-checkbox:checked.~filters-label {
опечатка с точкой

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +.todos-toolbar button {
у нас бэм, без каскадов

2019-10-24 17:03 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +	border: none;
кегль на кнопке отличается от контролов, да и гарнитура

2019-10-29 22:36 UTC, Eretic431 commented
старался как мог:( :taco: :seedling:

2019-10-30 10:05 UTC, fromanywhere requested changes

2019-10-30 10:05 UTC, fromanywhere commented on index.html
> +                <div class="custom-checkbox todos-list__item__ready-marker">
todos-list__item__ready-marker и далее не по бэму — не может быть два раза по __, https://habr.com/ru/post/305548/

2019-10-30 10:05 UTC, fromanywhere commented on index.html
> +            <div class="todos-list__item __completed">
чисто технически должно быть что-то в духе todos-list__item todos-list__item_completed

2019-10-30 10:05 UTC, fromanywhere commented on styles/base/custom-checkbox/custom-checkbox.css
> +}
на фокус бы тоже что-то подобное

2019-10-30 10:05 UTC, fromanywhere commented on styles/base/custom-textarea/custom-textarea.css
> +	height: 15px;
Вообще очень сомнительное решение с textarea, Вы же не сможете растянуть её под контент без js никак 
![image](https://user-images.githubusercontent.com/1042969/67847673-4e1dbc00-fb14-11e9-80bc-663864d44acc.png)

2019-10-30 10:05 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +.todos-list__item:focus .todos-list__item__remove{
не будет фокус так работать. .todos-list__item__remove:focus будет ближе к правде

2019-10-30 10:05 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +	visibility: hidden;
visibility не даст фокуситься нормально. Возьмите хотя бы opacity что ли

2019-10-30 10:05 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +	visibility: hidden;
Вообще конечно position там надо брать, но с учетом местного флоата будет тяжеловато

2019-10-30 10:05 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +   border: 2px solid #cccccc;
прыгать же будет по горизонтали. Причем с учетом того, что у Вас чекед и фокус с бордерами разной ширины, это прямо нужно будет хорошо подумать, чтобы скомпенсировать

2019-10-30 10:05 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +      left: -1000000000px;
Кто больше? https://www.reddit.com/r/ProgrammerHumor/comments/58zwnu/the_only_way_to_deal_with_zindex/

2019-10-31 08:40 UTC, fromanywhere requested changes

2019-10-31 08:40 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +	outline: none;
из-за этого кнопка не фокусится

2019-10-31 08:40 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +	width: 100%;
box-sizing: border-box, иначе фокус зарезается

2019-10-31 08:40 UTC, fromanywhere commented on styles/project/todos-toolbar/todos-toolbar.css
> +  border: 2px solid #cccccc;
Всё еще прыгает. .item-filter__text {border: 2px transparent solid}

2019-10-31 08:40 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +	width: 100%;
Всё еще сомнительно 
![image](https://user-images.githubusercontent.com/1042969/67931550-27728a80-fbd3-11e9-9ad8-8ee6f7e36e6b.png)

2019-10-31 08:40 UTC, fromanywhere commented on styles/project/todo-creator/todo-creator.css
> +	font-style: norm;
Не норм

2019-10-31 14:49 UTC, Eretic431 commented on styles/project/todo-creator/todo-creator.css
> +	font-style: norm;
стыд

2019-10-31 14:49 UTC, Eretic431 commented on styles/project/todos-list/todos-list.css
> +	width: 100%;
а какое поведение должно быть?

2019-10-31 14:50 UTC, Eretic431 commented on styles/project/todos-list/todos-list.css
> +	width: 100%;
должно растянуться под весь текст, не обрезая его? @fromanywhere

2019-10-31 15:30 UTC, Eretic431 commented on styles/project/todo-creator/todo-creator.css
> +	outline: none;
я вроде чекнул, она фокусилась, все равно убрал

2019-11-04 13:01 UTC, fromanywhere commented on styles/project/todos-list/todos-list.css
> +	width: 100%;
Ну вообще да. Сейчас оно и по горизонтали не может, и по вертикали очень не очень

2019-11-04 13:04 UTC, fromanywhere approved these changes
Я мог бы тут дожимать про неудачное решение с textarea, но лучше Вы придете к этому пониманию самостоятельно, когда будете писать js на всё это

2019-11-04 14:47 UTC, merged